add

diff --git a/.github/workflows/website-deploy.yml b/.github/workflows/website-deploy.yml
--- a/.github/workflows/website-deploy.yml
+++ b/.github/workflows/website-deploy.yml
@@ -2,7 +2,7 @@ name: Deploy Website
 
 on:
   push:
-    branches: [ plugin_api_v2, add_deploy_trigger ]
+    branches: [ plugin_api_v2, add_deploy_trigger ] # <======
     # paths:
       # - 'plugins.json'
   workflow_dispatch:
@@ -19,4 +19,4 @@ jobs:
             -H "Authorization: Bearer ${{ secrets.DEPLOY_WEBSITE }}" \
             https://api.github.com/repos/Flow-Launcher/flow-launcher.github.io/dispatches \
             -d '{"event_type":"deploy"}')
-          if [ "$http_status" -ne 200 ]; then echo "Error: Deploy trigger failed, HTTP status code is $http_status"; exit 1; fi
+          if [ "$http_status" -ne 204 ]; then echo "Error: Deploy trigger failed, HTTP status code is $http_status"; exit 1; fi
